competitions/urls.py
from django.urls import path

from . import views

app_name = 'competitions'

urlpatterns = [
    path('', views.CompetitionListView.as_view(), name='competition_list'),
    path('<int:cpk>/team/<int:tpk>/', views.CompetitionTeamDetailView.as_view(), name='competition_team_detail'),
    path('<int:pk>/', views.CompetitionDetailView.as_view(), name='competition_detail'),
    path('create/', views.CompetitionCreateView.as_view(), name='competition_create'),
    path('edit/<int:pk>/', views.CompetitionUpdateView.as_view(), name='competition_edit'),
    path('schedule/<int:pk>/', views.MatchScheduleView.as_view(), name='schedule_list'),
    path('table/<int:pk>/', views.CompetitionTableLeagueView.as_view(), name='table'),
    path('add/match/', views.MatchCreateView.as_view(), name='add_match'),
    path('edit/match/<int:pk>/', views.MatchUpdateView.as_view(), name='edit_match'),
    path('delete/match/<int:pk>/', views.MatchDeleteView.as_view(), name='delete_match'),
    path('delete/<int:pk>/', views.CompetitionDeleteView.as_view(), name='competition_delete'),
    path('confirm/<int:pk>/type_schedule', views.ConfirmView.as_view(), name='competition_confirm'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('competitions/', include('competitions.urls')),
    path('players/', include('players.urls')),
    path('teams/', include('teams.urls')),
    path('users/', include('users.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('__debug__/', include('debug_toolbar.urls')),

]

home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns =[
    path('', views.HomeView.as_view(), name='home'),

]

teams/urls.py
from django.urls import path

from . import views

app_name = 'teams'

urlpatterns = [
    path('', views.TeamsListView.as_view(), name='teams_list'),
    path('create', views.TeamCreateView.as_view(), name='team_add'),
    path('<int:pk>/', views.TeamDetailView.as_view(), name='team_detail'),
    path('edit/<int:pk>/', views.TeamUpdateView.as_view(), name='team_edit'),
    path('delete/<int:pk>/', views.TeamDeleteView.as_view(), name='team_delete'),
    path('delete/playerforteam/<int:pk>/', views.DeletePlayerForTeamView.as_view(), name='delete_player_for_team'),
    path('add/player/', views.AddPlayerToTeam.as_view(), name='add_player_to_team'),



]

competitions/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse
from teams.models import Team
from players.models import Player


# Create your models here.


class Competition(models.Model):
    competition_name = models.CharField(max_length=60, verbose_name='Nazwa Rozgrywek', unique=True)
    teams = models.ManyToManyField(Team, verbose_name='Uczestnicy')
    owner = models.ForeignKey(get_user_model(), verbose_name='Właściciel', on_delete=models.CASCADE, null=True,
                              blank=True)

    def __str__(self):
        return self.competition_name

    def get_absolute_url(self):
        return reverse('competitions:competition_detail', args=[str(self.id)])


class Match(models.Model):
    match_date = models.DateTimeField(blank=True, null=True, verbose_name='Data meczu')
    home_team = models.ForeignKey(Team, related_name='team_home', on_delete=models.CASCADE,
                                  verbose_name='Drużyna gospodarzy')
    away_team = models.ForeignKey(Team, related_name='team_away', on_delete=models.CASCADE,
                                  verbose_name='Drużyna gości')
    competition = models.ForeignKey(Competition, on_delete=models.CASCADE, verbose_name='Rozgrywki')
    home_goal = models.PositiveIntegerField(blank=True, null=True, verbose_name='Bramki gospodarzy')
    away_goal = models.PositiveIntegerField(blank=True, null=True, verbose_name='Bramki gości')


class PlayerInTeam(models.Model):
    team = models.ForeignKey(Team, on_delete=models.CASCADE, verbose_name='Zespół w którym występuje:')
    player = models.ForeignKey(Player, on_delete=models.CASCADE, verbose_name='Nazwa zawodnika:')
    season = models.ForeignKey(Competition, on_delete=models.CASCADE, verbose_name='W rozgrywkach:')

    def __str__(self):
        return f'{self.player.fullname} w rozgrywkach {self.season.competition_name} zgłoszony jest przez {self.team.team_name}'

home/models.py
from django.db import models

# Create your models here.

teams/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse
# Create your models here.


class Team(models.Model):
    team_name = models.CharField(max_length=60, unique=True)
    owner = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.team_name

    def get_absolute_url(self):
        return reverse('teams:team_detail', args=[str(self.id)])

home/views.py
from django.views.generic import TemplateView

from competitions.models import Competition
from teams.models import Team


class HomeView(TemplateView):
    '''
    This view is used to display the home page
    '''
    template_name = 'home/home.html'

    def get_context_data(self, **kwargs):
        context = super(HomeView, self).get_context_data(**kwargs)
        context['user_team'] = Team.objects.filter(owner=self.request.user.id)
        context['user_competition'] = Competition.objects.filter(owner=self.request.user.id)
        return context

home/templates/home/home.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Home
{% endblock %}

{% block container %}
    {% if user.is_authenticated %}

    <h3>Witaj, {{ user.username }} na stronie organizacji rozgrywek. </h3>


    <h1 class="modal-title">Moje zespoły</h1>
    <table class="table table-dark table-striped">
        <tr>
            <th>Nr</th>
            <th>Nazwa zespołu</th>
            <th>Właściciel</th>
            {% if perms.teams.delete_team %}
                <th>Edytuj</th>
                <th>Usuń</th>
            {% endif %}
        </tr>
        <tr>
            {% for team in user_team %}
                <td>{{ forloop.counter }}.</td>
                <td><a href="{% url 'teams:team_detail' pk=team.pk %}"
                       class="btn btn-dark">{{ team.team_name }}</a></td>
                <td>{{ team.owner }}</td>
                {% if perms.teams.delete_team %}
                    <td>
                        <a href="{% url 'teams:team_edit' pk=team.pk %}" class="btn btn-info">Edytuj</a>
                    </td>
                    <td>
                        <a href="{% url 'teams:team_delete' pk=team.pk %}" class="btn btn-danger">Usuń</a>
                    </td>
                {% endif %}
                </tr>
            {% empty %}
                <h3> - Jeszcze nie dodano żadnych zespołów</h3>
            {% endfor %}
    </table>

        <a href="{% url 'teams:team_add' %}" class="btn btn-success">Dodaj Zespół</a>


    <h1 class="modal-title">Moje rozgrywki:</h1>
    <table class="table table-dark  table-striped">
        <tr>
            <th>Nr</th>
            <th>Nazwa rozgrywek</th>
            <th>Organizator</th>
            {% if perms.competitions.delete_competition %}
                <th>Pole edycji</th>
                <th>Usuń</th>
            {% endif %}
        </tr>
        {% for competition in user_competition %}
            <tr>
                <td>{{ forloop.counter }}.</td>
                <td><a href="{% url 'competitions:competition_detail' competition.pk %}"
                       class="btn btn-dark">{{ competition.competition_name }}</a></td>
                <td>{{ competition.owner }}</td>
                {% if perms.competitions.delete_competition %}
                    <td><a href="{% url 'competitions:competition_edit' pk=competition.pk %}"
                           class="btn btn-info">Edytuj</a></td>
                    <td><a href="{% url 'competitions:competition_delete' pk=competition.pk %}"
                           class="btn btn-danger">Usuń</a></td>
                {% endif %}
            </tr>
        {% empty %}
            <h3> - Jeszcze nie dodano żadnych rozgrywek</h3>
        {% endfor %}
    </table>
            <a href="{% url 'competitions:competition_create' %}" class="btn btn-success">Dodaj rozgrywki</a>

    {% else %}

    <h3>Witaj, nieznajomy na stronie menagera rozgrywek. </h3>
    <a href="{% url 'login' %}" class="btn btn-primary">Zaloguj się</a>
    {% endif %}


{% endblock %}