competitions/urls.py
from django.urls import path

from . import views

app_name = 'competitions'

urlpatterns = [
    path('', views.CompetitionListView.as_view(), name='competition_list'),
    path('<int:cpk>/team/<int:tpk>/', views.CompetitionTeamDetailView.as_view(), name='competition_team_detail'),
    path('<int:pk>/', views.CompetitionDetailView.as_view(), name='competition_detail'),
    path('create/', views.CompetitionCreateView.as_view(), name='competition_create'),
    path('edit/<int:pk>/', views.CompetitionUpdateView.as_view(), name='competition_edit'),
    path('schedule/<int:pk>/', views.MatchScheduleView.as_view(), name='schedule_list'),
    path('table/<int:pk>/', views.CompetitionTableLeagueView.as_view(), name='table'),
    path('add/match/', views.MatchCreateView.as_view(), name='add_match'),
    path('edit/match/<int:pk>/', views.MatchUpdateView.as_view(), name='edit_match'),
    path('delete/match/<int:pk>/', views.MatchDeleteView.as_view(), name='delete_match'),
    path('delete/<int:pk>/', views.CompetitionDeleteView.as_view(), name='competition_delete'),
    path('confirm/<int:pk>/type_schedule', views.ConfirmView.as_view(), name='competition_confirm'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('competitions/', include('competitions.urls')),
    path('players/', include('players.urls')),
    path('teams/', include('teams.urls')),
    path('users/', include('users.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('__debug__/', include('debug_toolbar.urls')),

]

home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns =[
    path('', views.HomeView.as_view(), name='home'),

]

players/urls.py
from django.urls import path

from . import views

app_name = 'players'

urlpatterns = [
    path('', views.PlayerListView.as_view(), name='player_list'),
    path('create/', views.PlayerCreateView.as_view(), name='player_add'),
    path('<int:pk>/', views.PlayerDetailView.as_view(), name='player_detail'),
    path('edit/<int:pk>/', views.PlayerUpdateView.as_view(), name='player_edit'),
    path('delete/<int:pk>/', views.PlayerDeleteView.as_view(), name='player_delete'),

]

teams/urls.py
from django.urls import path

from . import views

app_name = 'teams'

urlpatterns = [
    path('', views.TeamsListView.as_view(), name='teams_list'),
    path('create', views.TeamCreateView.as_view(), name='team_add'),
    path('<int:pk>/', views.TeamDetailView.as_view(), name='team_detail'),
    path('edit/<int:pk>/', views.TeamUpdateView.as_view(), name='team_edit'),
    path('delete/<int:pk>/', views.TeamDeleteView.as_view(), name='team_delete'),
    path('delete/playerforteam/<int:pk>/', views.DeletePlayerForTeamView.as_view(), name='delete_player_for_team'),
    path('add/player/', views.AddPlayerToTeam.as_view(), name='add_player_to_team'),



]

users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('registration/', views.RegistrationUserView.as_view(), name='registration'),

]

templates/partials/_menu.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-3">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">GALP</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'home:home' %}">Home</a>
                </li>
                {% if not user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'login' %}">Zaloguj się</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page"
                           href="{% url 'users:registration' %}">Rejestracja</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page"
                           href="{% url 'logout' %}">Wyloguj {{ user.username }}</a>
                    </li>

                {% endif %}
                <div class="dropdown">
                    <button class="btn btn-dark dropdown-toggle" type="button" id="dropdownMenuButton2"
                            data-bs-toggle="dropdown" aria-expanded="false">
                        Rozgrywki
                    </button>
                    <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="dropdownMenuButton2">
                        <li><a class="dropdown-item active" href="{% url 'competitions:competition_list' %}">Lista
                            rozgrywek</a></li>
                        {% if perms.competitions.add_competition %}
                            <li><a class="dropdown-item" href="{% url 'competitions:competition_create' %}">Dodaj
                                rozgrywki</a></li>
                        {% endif %}
                    </ul>
                </div>
                <div class="dropdown">
                    <button class="btn btn-dark dropdown-toggle" type="button" id="dropdownMenuButton2"
                            data-bs-toggle="dropdown" aria-expanded="false">
                        Zespoły
                    </button>
                    <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="dropdownMenuButton2">
                        <li><a class="dropdown-item active" href="{% url 'teams:teams_list' %}">Lista
                            Zespołów</a></li>
                            <li><a class="dropdown-item" href="{% url 'teams:team_add' %}">Dodaj
                                Zespół</a></li>
                            <li><a class="dropdown-item" href="{% url 'teams:add_player_to_team' %}">Dodaj zawodnika do
                                zespołu</a>
                            </li>
                    </ul>
                </div>
                <div class="dropdown">
                    <button class="btn btn-dark dropdown-toggle" type="button" id="dropdownMenuButton2"
                            data-bs-toggle="dropdown" aria-expanded="false">Zawodnicy
                    </button>
                    <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="dropdownMenuButton2">
                        <li><a class="dropdown-item active" href="{% url 'players:player_list' %}">Lista
                            Zawodników</a></li>
{#                        {% if perms.players.add_player %}#}
                            <li><a class="dropdown-item" href="{% url 'players:player_add' %}">Dodaj Zawodnika</a></li>
{#                        {% endif %}#}
                    </ul>
                </div>
            </ul>

        </div>
    </div>
</nav>