config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('competitions/', include('competitions.urls')),
    path('players/', include('players.urls')),
    path('teams/', include('teams.urls')),
    path('users/', include('users.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('__debug__/', include('debug_toolbar.urls')),

]

home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns =[
    path('', views.HomeView.as_view(), name='home'),

]

teams/urls.py
from django.urls import path

from . import views

app_name = 'teams'

urlpatterns = [
    path('', views.TeamsListView.as_view(), name='teams_list'),
    path('create', views.TeamCreateView.as_view(), name='team_add'),
    path('<int:pk>/', views.TeamDetailView.as_view(), name='team_detail'),
    path('edit/<int:pk>/', views.TeamUpdateView.as_view(), name='team_edit'),
    path('delete/<int:pk>/', views.TeamDeleteView.as_view(), name='team_delete'),
    path('delete/playerforteam/<int:pk>/', views.DeletePlayerForTeamView.as_view(), name='delete_player_for_team'),
    path('add/player/', views.AddPlayerToTeam.as_view(), name='add_player_to_team'),



]

competitions/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse
from teams.models import Team
from players.models import Player


# Create your models here.


class Competition(models.Model):
    competition_name = models.CharField(max_length=60, verbose_name='Nazwa Rozgrywek', unique=True)
    teams = models.ManyToManyField(Team, verbose_name='Uczestnicy')
    owner = models.ForeignKey(get_user_model(), verbose_name='Właściciel', on_delete=models.CASCADE, null=True,
                              blank=True)

    def __str__(self):
        return self.competition_name

    def get_absolute_url(self):
        return reverse('competitions:competition_detail', args=[str(self.id)])


class Match(models.Model):
    match_date = models.DateTimeField(blank=True, null=True, verbose_name='Data meczu')
    home_team = models.ForeignKey(Team, related_name='team_home', on_delete=models.CASCADE,
                                  verbose_name='Drużyna gospodarzy')
    away_team = models.ForeignKey(Team, related_name='team_away', on_delete=models.CASCADE,
                                  verbose_name='Drużyna gości')
    competition = models.ForeignKey(Competition, on_delete=models.CASCADE, verbose_name='Rozgrywki')
    home_goal = models.PositiveIntegerField(blank=True, null=True, verbose_name='Bramki gospodarzy')
    away_goal = models.PositiveIntegerField(blank=True, null=True, verbose_name='Bramki gości')


class PlayerInTeam(models.Model):
    team = models.ForeignKey(Team, on_delete=models.CASCADE, verbose_name='Zespół w którym występuje:')
    player = models.ForeignKey(Player, on_delete=models.CASCADE, verbose_name='Nazwa zawodnika:')
    season = models.ForeignKey(Competition, on_delete=models.CASCADE, verbose_name='W rozgrywkach:')

    def __str__(self):
        return f'{self.player.fullname} w rozgrywkach {self.season.competition_name} zgłoszony jest przez {self.team.team_name}'

teams/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse
# Create your models here.


class Team(models.Model):
    team_name = models.CharField(max_length=60, unique=True)
    owner = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.team_name

    def get_absolute_url(self):
        return reverse('teams:team_detail', args=[str(self.id)])

teams/forms.py
from django import forms

from competitions.models import PlayerInTeam, Competition
from teams.models import Team


class PlayerInTeamForm(forms.ModelForm):

    class Meta:
        model = PlayerInTeam
        fields = ('team', 'player', 'season')

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user')
        super(PlayerInTeamForm, self).__init__(*args, **kwargs)
        if not user.is_staff:
            if len(Competition.objects.filter(owner=user)) == 0:
                self.fields['team'].queryset = Team.objects.filter(owner=user)
                self.fields['season'].queryset = Competition.objects.filter(teams__in=Team.objects.filter(owner=user))
            else:
                self.fields['team'].queryset = Team.objects.filter(competition__owner_id=user).distinct()
                self.fields['season'].queryset = Competition.objects.filter(owner=user)

    def clean(self):
        team = self.cleaned_data['team']
        team = team.id
        player = self.cleaned_data['player']
        player = player.id
        competition = self.cleaned_data['season']
        competition = competition.id
        players = PlayerInTeam.objects.filter(season_id=competition).values_list('player_id', flat=True)
        if player in players:
            raise forms.ValidationError('Zawodnik jest już przypisany w tych rozgrywkach')
        teams = Team.objects.filter(competition=competition).values_list('id', flat=True)
        if team not in teams:
            raise forms.ValidationError('Drużyna nie uczestniczy w tych rozgrywkach')
        return self.cleaned_data

teams/views.py
import os

from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.models import Group
from django.shortcuts import render, redirect
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from teams.forms import PlayerInTeamForm
from teams.models import Team
from competitions.models import PlayerInTeam


class TeamsListView(ListView):
    '''
    This view is used to display the list of teams
    '''
    model = Team
    template_name = 'teams/teams_list.html'
    context_object_name = 'teams'


class TeamCreateView(LoginRequiredMixin, CreateView):
    '''
    View of the team creating form
    '''
    model = Team
    fields = ('team_name',)
    template_name = 'teams/teams_add.html'
    login_url = reverse_lazy('login')

    def form_valid(self, form):
        user = get_user_model().objects.get(username=self.request.user)
        group = Group.objects.get(name=os.environ.get('DJ_GROUP_TEAM_OWNER'))
        user.groups.add(group)
        self.object = form.save(commit=False)
        self.object.owner = self.request.user
        self.object.save()
        return redirect(reverse_lazy('teams:teams_list'))


class TeamDetailView(DetailView):
    '''
    This view is used to display team details
    '''
    model = Team
    template_name = 'teams/team_detail.html'
    context_object_name = 'teams'


class TeamUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    '''
    View of the team editing form
    '''
    model = Team
    fields = ('team_name', 'owner')
    template_name = 'teams/team_edit.html'
    success_url = reverse_lazy('teams:teams_list')
    login_url = reverse_lazy('teams:teams_list')
    permission_required = 'teams.change_team'

    def dispatch(self, request, *args, **kwargs):
        obj = self.get_object()
        if obj.owner == self.request.user or self.request.user.is_staff:
            return super(TeamUpdateView, self).dispatch(request, *args, **kwargs)
        else:
            messages.error(request,
                        '''
                        Tylko właściciel lub administrator może edytować zespół!
                        Jeśli nie możesz zedytować swojej drużyny skontaktuj się z Administratorem strony.
                        '''
                        )
            return redirect('teams:teams_list')

    def form_valid(self, form):
        self.object = form.save(commit=False)
        group = Group.objects.get(name=os.environ.get('DJ_GROUP_TEAM_OWNER'))
        if form.cleaned_data['owner']:
            user = get_user_model().objects.get(username=form.cleaned_data['owner'])
            user.groups.add(group)
        self.object.save()
        return redirect(reverse_lazy('teams:teams_list'))


class TeamDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    '''
    View of the delete team
    '''
    model = Team
    success_url = reverse_lazy('teams:teams_list')
    login_url = reverse_lazy('teams:teams_list')
    permission_required = 'teams.delete_team'

    def dispatch(self, request, *args, **kwargs):
        obj = self.get_object()
        if obj.owner == self.request.user or self.request.user.is_staff:
            return super(TeamDeleteView, self).dispatch(request, *args, **kwargs)
        else:
            messages.error(request, 'Tylko właściciel lub administrator może usunąć zespół!')
            return redirect('teams:teams_list')


class AddPlayerToTeam(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    '''
    View of the form adding a player to the team in specific competitions
    '''

    form_class = PlayerInTeamForm
    template_name = 'teams/add_player_team.html'
    login_url = reverse_lazy('login')
    permission_required = 'competitions.add_playerinteam'

    def get_form_kwargs(self):
        kwargs = super(AddPlayerToTeam, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def get_success_url(self, **kwargs):
        return reverse_lazy('teams:team_detail', kwargs={'pk': self.object.team_id})


class DeletePlayerForTeamView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    '''
     View deleting a player to the team in specific competitions
    '''
    model = PlayerInTeam
    login_url = reverse_lazy('teams:teams_list')
    permission_required = 'competitions.delete_playerinteam'

    def get_success_url(self, **kwargs):
        return reverse_lazy('teams:team_detail', kwargs={'pk': self.object.team_id})

teams/templates/teams/add_player_team.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
    Dodaj zespół
{% endblock %}

{% block container %}
    <form action="" method="post">
    {% csrf_token %}
    <h2>Dodawanie zawodnika do zespołu</h2>

    {{ form|crispy }}

    <button type="submit" class="btn btn-success">Dodaj zawodnika</button>
    </form>

{% endblock %}

teams/templates/teams/team_confirm_delete.html
{% extends 'base.html' %}
{% block title %}
    Kasowanie zespołu
{% endblock %}
{% block container %}
    <form action="" method="post">
        {% csrf_token %}
        <h2>Kasowanie zespołu</h2>
        <h3 class="alert-danger">Czy na pewno chcesz usunąć zespół {{ team.team_name }}</h3>
        <button type="button" class="btn btn-warning">
            <a href="{% url 'teams:teams_list' %}">Anuluj</a>
        </button>
        <button type="submit" class="btn btn-danger">Potwierdź</button>
    </form>



{% endblock %}

teams/templates/teams/team_detail.html
{% extends 'base.html' %}

{% block title %}
    Szczegóły
{% endblock %}

{% block container %}

    <h1> Nazwa Zespołu: {{ teams.team_name }}</h1>
    <h1> Właściciel Zespołu: {{ teams.owner }}</h1>
    <h3>W drużynie występowali: </h3>
    <table class="table table-dark table-striped">
        <tr>
            <th>Nr</th>
            <th>Kto tu grał i w jakich rozgrywkach</th>
            {% if perms.competitions.delete_playerinteam %}
                <th>Usuń</th>
            {% endif %}
        </tr>
        {% for team in teams.playerinteam_set.all %}
            <tr>
                <td> {{ forloop.counter }}.</td>
                <td>{{ team.player }} w rozgrywkach {{ team.season }}</td>
                {% if perms.competitions.delete_playerinteam %}
                    <td><a href="{% url 'teams:delete_player_for_team' pk=team.pk %}" class="btn btn-danger">Usuń</a>
                    </td>
                {% endif %}
            </tr>
        {% endfor %}
    </table>


    <h3>Drużyna gra w rozgrywkach: </h3>
    <table class="table table-dark table-striped ">
        <tr>
            <th>Nr</th>
            <th>Nazwa Rozgrywek:</th>
        </tr>
        {% for team in teams.competition_set.all %}
            <tr>
                <td> {{ forloop.counter }}.</td>
                <td> {{ team.competition_name }}</td>

            </tr>
        {% endfor %}
    </table>
{% endblock %}

teams/templates/teams/team_edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
    Edytuj zespół
{% endblock %}

{% block container %}
    <form action="" method="post">
    {% csrf_token %}
    <h2>Edycja Zespołu</h2>

    {{ form|crispy }}

    <button type="submit" class="btn btn-success">Zapisz zmiany</button>
    </form>

{% endblock %}

teams/templates/teams/teams_add.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
    Dodaj zespół
{% endblock %}

{% block container %}
    <form action="" method="post">
    {% csrf_token %}
    <h2>Dodawanie Zespołu</h2>

    {{ form|crispy }}

    <button type="submit" class="btn btn-success">Dodaj drużynę</button>
    </form>

{% endblock %}

teams/templates/teams/teams_list.html
{% extends 'base.html' %}

{% block title %}
    Lista zespołów
{% endblock %}


{% block container %}

    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-danger">{{ message }}</div>
        {% endfor %}
    {% endif %}
    <h1 class="modal-title">Lista zespołów</h1>
    <table class="table table-dark table-striped">
        <tr>
            <th>Nr</th>
            <th>Nazwa zespołu</th>
            <th>Właściciel</th>
            {% if perms.teams.delete_team %}
                <th>Edytuj</th>
                <th>Usuń</th>
            {% endif %}
        </tr>
        <tr>
            {% for team in teams %}
                <td>{{ forloop.counter }}.</td>

                <td><a href="{% url 'teams:team_detail' pk=team.pk %}"
                       class="btn btn-dark">{{ team.team_name }}</a></td>
                <td>{{ team.owner }}</td>
                {% if perms.teams.delete_team %}
                    <td>
                        <a href="{% url 'teams:team_edit' pk=team.pk %}" class="btn btn-info">Edytuj</a>
                    </td>
                    <td>
                        <a href="{% url 'teams:team_delete' pk=team.pk %}" class="btn btn-danger">Usuń</a>
                    </td>
                {% endif %}
                </tr>
            {% empty %}
                <h3> - Jeszcze nie dodano żadnych zespołów</h3>
            {% endfor %}
    </table>

{% endblock %}