competitions/urls.py
from django.urls import path

from . import views

app_name = 'competitions'

urlpatterns = [
    path('', views.CompetitionListView.as_view(), name='competition_list'),
    path('<int:cpk>/team/<int:tpk>/', views.CompetitionTeamDetailView.as_view(), name='competition_team_detail'),
    path('<int:pk>/', views.CompetitionDetailView.as_view(), name='competition_detail'),
    path('create/', views.CompetitionCreateView.as_view(), name='competition_create'),
    path('edit/<int:pk>/', views.CompetitionUpdateView.as_view(), name='competition_edit'),
    path('schedule/<int:pk>/', views.MatchScheduleView.as_view(), name='schedule_list'),
    path('table/<int:pk>/', views.CompetitionTableLeagueView.as_view(), name='table'),
    path('add/match/', views.MatchCreateView.as_view(), name='add_match'),
    path('edit/match/<int:pk>/', views.MatchUpdateView.as_view(), name='edit_match'),
    path('delete/match/<int:pk>/', views.MatchDeleteView.as_view(), name='delete_match'),
    path('delete/<int:pk>/', views.CompetitionDeleteView.as_view(), name='competition_delete'),
    path('confirm/<int:pk>/type_schedule', views.ConfirmView.as_view(), name='competition_confirm'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('competitions/', include('competitions.urls')),
    path('players/', include('players.urls')),
    path('teams/', include('teams.urls')),
    path('users/', include('users.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('__debug__/', include('debug_toolbar.urls')),

]

home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns =[
    path('', views.HomeView.as_view(), name='home'),

]

teams/urls.py
from django.urls import path

from . import views

app_name = 'teams'

urlpatterns = [
    path('', views.TeamsListView.as_view(), name='teams_list'),
    path('create', views.TeamCreateView.as_view(), name='team_add'),
    path('<int:pk>/', views.TeamDetailView.as_view(), name='team_detail'),
    path('edit/<int:pk>/', views.TeamUpdateView.as_view(), name='team_edit'),
    path('delete/<int:pk>/', views.TeamDeleteView.as_view(), name='team_delete'),
    path('delete/playerforteam/<int:pk>/', views.DeletePlayerForTeamView.as_view(), name='delete_player_for_team'),
    path('add/player/', views.AddPlayerToTeam.as_view(), name='add_player_to_team'),



]

competitions/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse
from teams.models import Team
from players.models import Player


# Create your models here.


class Competition(models.Model):
    competition_name = models.CharField(max_length=60, verbose_name='Nazwa Rozgrywek', unique=True)
    teams = models.ManyToManyField(Team, verbose_name='Uczestnicy')
    owner = models.ForeignKey(get_user_model(), verbose_name='Właściciel', on_delete=models.CASCADE, null=True,
                              blank=True)

    def __str__(self):
        return self.competition_name

    def get_absolute_url(self):
        return reverse('competitions:competition_detail', args=[str(self.id)])


class Match(models.Model):
    match_date = models.DateTimeField(blank=True, null=True, verbose_name='Data meczu')
    home_team = models.ForeignKey(Team, related_name='team_home', on_delete=models.CASCADE,
                                  verbose_name='Drużyna gospodarzy')
    away_team = models.ForeignKey(Team, related_name='team_away', on_delete=models.CASCADE,
                                  verbose_name='Drużyna gości')
    competition = models.ForeignKey(Competition, on_delete=models.CASCADE, verbose_name='Rozgrywki')
    home_goal = models.PositiveIntegerField(blank=True, null=True, verbose_name='Bramki gospodarzy')
    away_goal = models.PositiveIntegerField(blank=True, null=True, verbose_name='Bramki gości')


class PlayerInTeam(models.Model):
    team = models.ForeignKey(Team, on_delete=models.CASCADE, verbose_name='Zespół w którym występuje:')
    player = models.ForeignKey(Player, on_delete=models.CASCADE, verbose_name='Nazwa zawodnika:')
    season = models.ForeignKey(Competition, on_delete=models.CASCADE, verbose_name='W rozgrywkach:')

    def __str__(self):
        return f'{self.player.fullname} w rozgrywkach {self.season.competition_name} zgłoszony jest przez {self.team.team_name}'

competitions/forms.py
from django import forms

from teams.models import Team
from .models import Competition, Match


class CompetitionForm(forms.ModelForm):
    class Meta:
        model = Competition
        fields = ('competition_name', 'teams',)


class MatchForm(forms.ModelForm):
    match_date = forms.DateTimeField(label='Data meczu', required=False,
                                     widget=forms.DateTimeInput(attrs={'placeholder': 'RRRR-MM-DD GG-MM-SS'}))

    class Meta:
        model = Match
        fields = ('match_date', 'home_team', 'away_team', 'competition', 'home_goal', 'away_goal')

    def clean(self):
        team_home = self.cleaned_data['home_team']
        team_away = self.cleaned_data['away_team']
        teams = Team.objects.filter(competition=self.cleaned_data['competition'])
        if team_home not in teams or team_away not in teams:
            raise forms.ValidationError('Wybrałeś drużynę która nie występuje w tych rozgrywkach')
        if team_home == team_away:
            raise forms.ValidationError('Wybrałeś te same drużyny')
        return self.cleaned_data

competitions/views.py
import os
from random import shuffle
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.models import Group
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from teams.models import Team
from .forms import CompetitionForm, MatchForm
from .models import Competition, Match, PlayerInTeam


class CompetitionListView(ListView):
    '''
    This view is used to display the list of Competitions
    '''
    model = Competition
    template_name = 'competitions/competitions_list.html'
    context_object_name = 'competitions'


class CompetitionDetailView(DetailView):
    '''
    This view to display competitions details
    '''
    model = Competition
    template_name = 'competitions/competitions_detail.html'
    context_object_name = 'competition'


class CompetitionCreateView(LoginRequiredMixin, CreateView):
    '''
    View of the competition creating form
    '''
    form_class = CompetitionForm
    success_url = reverse_lazy('competitions:competition_list')
    template_name = 'competitions/competition_create.html'
    login_url = reverse_lazy('login')

    def form_valid(self, form):
        self.object = form.save(commit=False)
        user = get_user_model().objects.get(username=self.request.user)
        group = Group.objects.get(name=os.environ.get('DJ_GROUP_COMPETITION_OWNER'))
        user.groups.add(group)
        self.object.owner = self.request.user
        self.object.save()
        return super(CompetitionCreateView, self).form_valid(form)


class CompetitionUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    '''
    View of the competition edit form
    '''
    fields = ('competition_name', 'teams', 'owner')
    model = Competition
    template_name = 'competitions/competition_edit.html'
    success_url = reverse_lazy('competitions:competition_list')
    login_url = reverse_lazy('competitions:competition_list')
    permission_required = 'competitions.change_competition'

    def dispatch(self, request, *args, **kwargs):
        obj = self.get_object()
        if obj.owner == self.request.user or self.request.user.is_staff:
            return super(CompetitionUpdateView, self).dispatch(request, *args, **kwargs)
        else:
            messages.error(request, 'Tylko właściciel lub administrator może edytować rozgrywki!')
            return redirect('competitions:competition_list')

    def form_valid(self, form):
        self.object = form.save(commit=False)
        if form.cleaned_data['owner']:
            group = Group.objects.get(name=os.environ.get('DJ_GROUP_COMPETITION_OWNER'))
            user = get_user_model().objects.get(username=form.cleaned_data['owner'])
            user.groups.add(group)
        self.object.save()
        return super(CompetitionUpdateView, self).form_valid(form)


class CompetitionDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    '''
    View of the competition delete form
    '''
    model = Competition
    success_url = reverse_lazy('competitions:competition_list')
    login_url = reverse_lazy('competitions:competition_list')
    permission_required = 'competitions.delete_competition'

    def dispatch(self, request, *args, **kwargs):
        obj = self.get_object()
        if obj.owner == self.request.user or self.request.user.is_staff:
            return super(CompetitionDeleteView, self).dispatch(request, *args, **kwargs)
        else:
            messages.error(request, 'Tylko właściciel lub administrator może usunąć rozgrywki!')
            return redirect('competitions:competition_list')


class CompetitionTeamDetailView(View):
    '''
    view details of the team playing in selected competitions.
    Using this view, we will find out what players are in this team in selected competitions
    '''

    def get(self, request, cpk, tpk):
        players = PlayerInTeam.objects.filter(season_id=cpk, team_id=tpk)
        competition = Competition.objects.get(pk=cpk)
        team = Team.objects.get(pk=tpk)
        return render(
            request,
            "competitions/competitions_team_detail.html",
            context={
                'competition': competition,
                'team': team,
                'players': players,
            })


class MatchScheduleView(DetailView):
    '''
    View of the schedule of selected competitions
    '''
    model = Competition
    template_name = 'competitions/schedule_list.html'
    context_object_name = 'competition'

    def post(self, request, pk):
        teams = list(Team.objects.filter(competition=pk).values_list('id', flat=True))
        shuffle(teams)
        if len(teams) % 2 != 0:
            teams.append(-1)
        if 'one_round' in request.POST:
            if len(Match.objects.filter(competition_id=pk)) == 0:
                create_schedule_one_round(teams, pk)
            else:
                type_schedule = 'one_round'
                request.session['type_schedule'] = type_schedule
                return redirect('competitions:competition_confirm', pk)
            return redirect('competitions:schedule_list', pk)
        elif 'two_round' in request.POST:
            if len(Match.objects.filter(competition_id=pk)) == 0:
                create_schedule_two_round(teams, pk)
            else:
                type_schedule = 'two_round'
                request.session['type_schedule'] = type_schedule
                return redirect('competitions:competition_confirm', pk)
            return redirect('competitions:schedule_list', pk)


class MatchCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    '''
    View of the match/game creating form
    '''
    form_class = MatchForm
    login_url = reverse_lazy('competitions:competition_list')
    template_name = 'competitions/add_match.html'
    permission_required = 'competitions.add_match'

    def get_success_url(self, **kwargs):
        return reverse_lazy('competitions:schedule_list', kwargs={'pk': self.object.competition_id})
# TODO default tournament name and team filter and add more statistic to game (player score, cards etc.)

class MatchUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    '''
    View of the match/game creating form
    '''
    model = Match
    form_class = MatchForm
    login_url = reverse_lazy('competitions:competition_list')
    template_name = 'competitions/edit_match.html'
    permission_required = 'competitions.change_match'

    def get_success_url(self, **kwargs):
        return reverse_lazy('competitions:schedule_list', kwargs={'pk': self.object.competition_id})


class MatchDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    '''
    View of the match/game delete form
    '''
    model = Match
    login_url = reverse_lazy('competitions:competition_list')
    permission_required = 'competitions.delete_match'

    def get_success_url(self, **kwargs):
        return reverse_lazy('competitions:schedule_list', kwargs={'pk': self.object.competition_id})


class CompetitionTableLeagueView(View):
    '''
    view details all teams playing in selected competitions.
    using this view, we create tables with points scored by the team in selected competitions based
    on the results of matches in selected competitions
    '''

    def get(self, request, pk):
        matches = Match.objects.filter(competition_id=pk, home_goal__isnull=False, away_goal__isnull=False)
        competition = Competition.objects.get(pk=pk)
        teams = Team.objects.filter(competition=pk)
        table = {}
        for team in teams:
            table.update({team.team_name: {'games': 0, 'goals scored': 0, 'goals conceded': 0, 'points': 0}})
        for match in matches:
            table[match.home_team.team_name]['games'] += 1
            table[match.away_team.team_name]['games'] += 1
            table[match.home_team.team_name]['goals scored'] += match.home_goal
            table[match.home_team.team_name]['goals conceded'] += match.away_goal
            table[match.away_team.team_name]['goals scored'] += match.away_goal
            table[match.away_team.team_name]['goals conceded'] += match.home_goal
            if match.home_goal > match.away_goal:
                table[match.home_team.team_name]['points'] += 3
            elif match.away_goal > match.home_goal:
                table[match.away_team.team_name]['points'] += 3
            else:
                table[match.away_team.team_name]['points'] += 1
                table[match.home_team.team_name]['points'] += 1
        table_league = sorted(table, key=lambda k: (table[k]['points'], table[k]['goals scored']), reverse=True)
        return render(
            request,
            "competitions/table.html",
            context={
                'competition': competition,
                'teams': teams,
                'table_league': table_league,
                'table': table,
            })
# TODO add more statistic to table

class ConfirmView(View):

    def get(self, request, pk):
        competition = Competition.objects.get(id=pk)
        return render(request, 'competitions/schedule_confirm.html', context={'competition': competition})

    def post(self, request, pk):
        teams = list(Team.objects.filter(competition=pk).values_list('id', flat=True))
        shuffle(teams)
        if len(teams) % 2 != 0:
            teams.append(-1)
        Match.objects.filter(competition_id=pk).delete()
        if request.session['type_schedule'] == 'one_round':
            create_schedule_one_round(teams, pk)
        elif request.session['type_schedule'] == 'two_round':
            create_schedule_two_round(teams, pk)
        return redirect('competitions:schedule_list', pk)


def next_move(teams):

competitions/templates/competitions/add_match.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
    Dodawanie meczu
{% endblock %}
{% block container %}
    <form action="" method="post">
        {% csrf_token %}
        <h2>Dodawanie meczu</h2>
        {{ form|crispy }}
        <button type="submit" class="btn btn-success">Dodaj mecz</button>
    </form>



{% endblock %}

competitions/templates/competitions/competition_confirm_delete.html
{% extends 'base.html' %}
{% block title %}
    Kasowanie rozgrywek
{% endblock %}
{% block container %}
    <form action="" method="post">
        {% csrf_token %}
        <h2>Kasowanie rozgrywek</h2>
        <h3 class="alert-danger">Czy na pewno chcesz usunąć rozgrywki {{ competition.competition_name }}</h3>
        <button type="button" class="btn btn-warning">
            <a href="{% url 'competitions:competition_list' %}">Anuluj</a>
        </button>
        <button type="submit" class="btn btn-danger">Potwierdź</button>
    </form>



{% endblock %}

competitions/templates/competitions/competition_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
    Tworzenie rozgrywek
{% endblock %}
{% block container %}
    <form action="" method="post">
        {% csrf_token %}
        <h2>Tworzenie rozgrywek</h2>
        {{ form|crispy }}
        <button type="submit" class="btn btn-success">Dodaj rozgrywki</button>
    </form>



{% endblock %}

competitions/templates/competitions/competition_edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
    Edycja rozgrywek
{% endblock %}
{% block container %}
    <form action="" method="post">
        {% csrf_token %}
        <h2>Edycja rozgrywek</h2>
        {{ form|crispy }}
        <button type="submit" class="btn btn-success">Zapisz zmiany</button>
    </form>



{% endblock %}

competitions/templates/competitions/competitions_detail.html
{% extends 'base.html' %}

{% block title %}
    Szczegóły
{% endblock %}

{% block container %}


    <div class="btn-group btn-group-lg" role="group" aria-label="Basic example">
        <button type="button" class="btn btn-dark"><a href="{% url 'competitions:table' pk=competition.pk %}"
                                                      class="btn btn-dark"> Tabela </a></button>
        <button type="button" class="btn btn-dark"><a href="{% url 'competitions:schedule_list' pk=competition.pk %}"
                                                      class="btn btn-dark"> Terminarz </a></button>
        <button type="button" class="btn btn-dark"><a href="{% url 'competitions:competition_list' %}"
                                                      class="btn btn-dark"> Lista Rozgrywek </a></button>
    </div>

    <h1> Rozgrywki: {{ competition.competition_name }}</h1>
    <table class="table table-dark  table-striped">
        <tr>
            <th>Nr</th>
            <th>Nazwa zespołu</th>
            <th>Właściciel Zespołu</th>
        </tr>
        {% for team in competition.teams.all %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td><a href="{% url 'competitions:competition_team_detail' cpk=competition.pk tpk=team.pk %}"
                       class="btn btn-dark"> {{ team.team_name }} </a></td>
                <td>{{ team.owner }}</td>
            </tr>
        {% endfor %}
    </table>

{% endblock %}

competitions/templates/competitions/competitions_list.html
{% extends 'base.html' %}

{% block title %}
    Lista rozgrywek
{% endblock %}

{% block container %}
    <h1 class="modal-title">Lista rozgrywek:</h1>

    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-danger">{{ message }}</div>
        {% endfor %}
    {% endif %}

    <table class="table table-dark  table-striped">
        <tr>
            <th>Nr</th>
            <th>Nazwa rozgrywek</th>
            <th>Organizator</th>
            {% if perms.competitions.delete_competition %}
                <th>Pole edycji</th>
                <th>Usuń</th>
            {% endif %}
        </tr>
        {% for competition in competitions %}
            <tr>
                <td>{{ forloop.counter }}.</td>
                <td><a href="{% url 'competitions:competition_detail' competition.pk %}"
                       class="btn btn-dark">{{ competition.competition_name }}</a></td>
                <td>{{ competition.owner }}</td>
                {% if perms.competitions.delete_competition %}
                    <td><a href="{% url 'competitions:competition_edit' pk=competition.pk %}"
                           class="btn btn-info">Edytuj</a></td>
                    <td><a href="{% url 'competitions:competition_delete' pk=competition.pk %}"
                           class="btn btn-danger">Usuń</a></td>
                {% endif %}
            </tr>
        {% empty %}
            <h3> - Jeszcze nie dodano żadnych rozgrywek</h3>
        {% endfor %}
    </table>
{% endblock %}

competitions/templates/competitions/competitions_team_detail.html
{% extends 'base.html' %}

{% block title %}
    Szczegóły
{% endblock %}

{% block container %}

    <h1> Lista zgłoszonych zawodników drużyny {{ team.team_name }} w
        rozgrywkach {{ competition.competition_name }} </h1>
    <table class="table table-dark table-striped">
        <tr>
            <th>Nr</th>
            <th>Nazwa zawodnika:</th>
            {% if perms.competitions.delete_playerinteam %}
                <th>Usuń</th>
            {% endif %}
        </tr>
        {% for player in players %}
            <tr>
                <td> {{ forloop.counter }}.</td>
                <td>{{ player.player.fullname }} </td>
                {% if perms.competitions.delete_playerinteam %}
                    <td><a href="{% url 'teams:delete_player_for_team' pk=player.pk %}" class="btn btn-danger">Usuń</a>
                    </td>
                {% endif %}
            </tr>
        {% endfor %}
    </table>
{% endblock %}

competitions/templates/competitions/edit_match.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
    Edycja meczu
{% endblock %}
{% block container %}
    <form action="" method="post">
        {% csrf_token %}
        <h2>Edycja meczu</h2>
        {{ form|crispy }}
        <button type="submit" class="btn btn-success">Edytuj spotkanie</button>
    </form>



{% endblock %}

competitions/templates/competitions/match_confirm_delete.html
{% extends 'base.html' %}
{% block title %}
    Usuwanie spotkania
{% endblock %}
{% block container %}
    <form action="" method="post">
        {% csrf_token %}
        <h2>Usuwanie spotkania</h2>
        <h3 class="alert-danger">Czy na pewno chcesz usunąć spotkanie</h3>
        <button type="button" class="btn btn-warning">
            <a href="{% url 'competitions:competition_list' %}">Anuluj</a>
        </button>
        <button type="submit" class="btn btn-danger">Potwierdź</button>
    </form>



{% endblock %}

competitions/templates/competitions/playerinteam_confirm_delete.html
{% extends 'base.html' %}
{% block title %}
    Kasowanie zespołu
{% endblock %}
{% block container %}
    <form action="" method="post">
        {% csrf_token %}
        <h2>Kasowanie zespołu</h2>
        <h3 class="alert-danger">Czy na pewno chcesz usunąć zawodnika z zespołu {{ playerinteam.player }}</h3>
        <button type="button" class="btn btn-warning">
            <a href="{% url 'teams:teams_list' %}">Anuluj</a>
        </button>
        <button type="submit" class="btn btn-danger">Potwierdź</button>
    </form>



{% endblock %}

competitions/templates/competitions/schedule_confirm.html
{% extends 'base.html' %}
{% block title %}
    Generowanie terminarza
{% endblock %}
{% block container %}
    <form action="" method="post">
        {% csrf_token %}
        <h2>Powtórne Generowanie terminarza</h2>
        <h3 class="alert-danger">Czy na pewno chcesz na now wygenerować terminarz? Generowanie nowego terminarza, że
            wszystkie dotychczasowe mecze oraz wyniki zostaną bezpowrotnie usunięte!</h3>
        <button type="button" class="btn btn-warning">
            <a href="{% url 'competitions:schedule_list' pk=competition.id %}">Anuluj</a>
        </button>
        <button type="submit" class="btn btn-danger">Potwierdź</button>
    </form>



{% endblock %}

competitions/templates/competitions/schedule_list.html
{% extends 'base.html' %}

{% block title %}
    Terminarz rozgrywek
{% endblock %}

{% block container %}
    <div class="btn-group btn-group-lg" role="group" aria-label="Basic example">
        <button type="button" class="btn btn-dark"><a href="{% url 'competitions:table' pk=competition.pk %}"
                                                      class="btn btn-dark"> Tabela </a></button>
        <button type="button" class="btn btn-dark"><a href="{% url 'competitions:schedule_list' pk=competition.pk %}"
                                                      class="btn btn-dark"> Terminarz </a></button>
        <button type="button" class="btn btn-dark"><a href="{% url 'competitions:competition_list' %}"
                                                      class="btn btn-dark"> Lista Rozgrywek </a></button>
    </div>


    <h1 class="modal-title">Terminarz rozgrywek: {{ competition.competition_name }}</h1>

    {% if perms.competitions.add_match and user == competition.owner or user.is_staff %}
        <div class="btn-group btn-group-lg" role="group" aria-label="Basic example">
            <form action="" method="post">
                {% csrf_token %}
                <button type="submit" name="one_round" class="btn btn-success">Generuj terminarz (jedna runda)</button>
            </form>
            <form action="" method="post">
                {% csrf_token %}
                <button type="submit" name="two_round" class="btn btn-success">Generuj terminarz (dwie rundy)</button>
            </form>
        </div>
        <a href="{% url 'competitions:add_match' %}" class="btn btn-success">Dodaj mecz</a>
    {% endif %}

    <table class="table table-dark table-striped text-center">
        <tr>
            <th>Nr</th>
            <th>Data</th>
            <th>Gospodarz</th>
            <th>Gość</th>
            <th class="col-auto">Bramki Gospodarzy</th>
            <th class="col-auto">Bramki Gości</th>
            {% if perms.competitions.add_match and user == competition.owner or user.is_staff %}
                <th>Dodaj wynik</th>
                <th>Usuń spotkanie</th>
            {% endif %}
        </tr>
        {% for match in competition.match_set.all %}
            <tr>
                <td>{{ forloop.counter }}.</td>
                <td>{% if match.match_date == None %}Brak Daty{% else %}{{ match.match_date }}{% endif %}</td>
                <td>{{ match.home_team }}</td>
                <td>{{ match.away_team }}</td>
                <td>{% if match.home_goal == None %} - {% else %} {{ match.home_goal }}{% endif %} </td>
                <td> {% if match.away_goal == None %} - {% else %} {{ match.away_goal }}{% endif %} </td>
                {% if perms.competitions.add_match and user == competition.owner or user.is_staff %}
                    <td><a href="{% url 'competitions:edit_match' pk=match.pk %}" class="btn btn-info">Edytuj</a></td>
                    <td><a href="{% url 'competitions:delete_match' pk=match.pk %}" class="btn btn-danger">Usuń</a></td>
                {% endif %}
            </tr>
        {% empty %}
            <h3> - Jeszcze nie dodano żadnych meczy</h3>
        {% endfor %}
    </table>

{% endblock %}

competitions/templates/competitions/table.html
{% extends 'base.html' %}

{% block title %}
    Terminarz rozgrywek
{% endblock %}

{% block container %}
    <div class="btn-group btn-group-lg" role="group" aria-label="Basic example">
        <button type="button" class="btn btn-dark"><a href="{% url 'competitions:table' pk=competition.pk %}"
                                                      class="btn btn-dark"> Tabela </a></button>
        <button type="button" class="btn btn-dark"><a href="{% url 'competitions:schedule_list' pk=competition.pk %}"
                                                      class="btn btn-dark"> Terminarz </a></button>
        <button type="button" class="btn btn-dark"><a href="{% url 'competitions:competition_list' %}"
                                                      class="btn btn-dark"> Lista Rozgrywek </a></button>
    </div>

    <h1 class="modal-title">Tabela rozgrywek: {{ competition.competition_name }} </h1>

    <table class="table table-dark table-striped text-center">
        <tr>
            <th>Pozycja</th>
            <th>Nazwa Drużyny</th>
            <th>Liczba spotkań</th>
            <th>Bramki strzelone</th>
            <th>Bramki stracone</th>
            <th>Punkty</th>
        </tr>
        {% for team in table_league %}
            <tr>
            <td>{{ forloop.counter }}.</td>
            <td>{{ team }} </td>
            {% for key, value in table.items %}
                {% if team == key %}
                    {% for key, value in value.items %}
                        <td>{{ value }} </td>
                    {% endfor %}
                {% endif %}


            {% endfor %}
        {% endfor %}
    </table>

{% endblock %}